### PR TITLE
Pr/233 Revive - Soldier Caste

### PR DESCRIPTION
**Pull request by AmoryBlaine**
Reviving Soldiers, editing them to be less focused on barricade combat

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by AmoryBlaine** [comment]
Given the new update, and my lack of actual coding ability I can't update this to function with the new code

**Pull request closed without merging**
