### PR TITLE
add flamer fueltank pouches to the garrow

### PR DESCRIPTION
**Pull request by Ediblebomb**
Just adds two flamer fueltank pouches to the garrow next to the fuel box.
You get three tanks per flamethrower, so one in the flamethrower and two in the pouch, it's perfect.
The flamethrower already takes up your back slot, which is the easiest spot to store flamer tanks, instead of also taking up two pouches or your belt, JUST the backslot and a pouch seems much more reasonable.

### CODE REVIEW

**Comment by DexterDude** [comment]
add them to the vendors instead, it looks kinda ugly on the table.

**Review by DexterDude — DISMISSED** [review]
add them to the vendors instead, it looks kinda ugly on the table.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Doubleumc — APPROVED** [review]

**Pull request merged**
