### PR TITLE
US Armed Forces update 5 (More Army stuff this time)

### PR DESCRIPTION
**Pull request by BonniePandora**
# About the pull request

Adds the last of the frontline combat roles for the US Army, along with a few non-combat oriented ones.
The AT Gunner & Loader duo require teamwork in order to keep up the fire, the marksman packs a scoped rifle with limited ammunition and no night-vision capability, the grenadier carries more grenades to readily load into their UGL and the heavy gunner is the army's smartgunner.
Alongside that, an Intelligence Officer, Science Officer and Technical Engineer have been added (IO, Researcher and MT respectively)

Alongside the gear preset additions, the M5 RPG has had it's spec requirement removed (why does something the marines are presumably trained on at basic need special training to use in the field??) and can be carried on the back now.
If that's gonna be an issue, do let me know and I can revert that and mess with the AT gunners spec skill so they can use the toob

# Explain why it's good for the game

More prop variety for GMs to use as they see fit. Also added some presets requested from Kirsh.
Might border on bloat, can see about condensing it down if needed, remove many of the (lesser rank) entries.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

image
Crowd on the right is the new presets.
From left to right, upper then lower; AT Gunner, AT loader, Grenadier, Science Officer, Marksman, Heavy Gunner, Intel Officer, Technical Engineer.
image
New unit patch for the intel operative

</details>

# Changelog

:cl:
add: Multiple new US army presets
qol: M5 RPG can be used by all, and can be worn on the back now
qol: USASF and Army ranks lost the . after all their ranks on comms
balance: Army lost their mag-harnesses in favour of a red-dot optic as standard, at reqeust of Verbs
imageadd: New unit patch, new onmob for back-worn M5 RPG
/:cl:

### CODE REVIEW

**Comment by Eonoc** [comment]
This slight issue is soulful, but I'm just making sure it's intended: the AT gunner not having an ear protection helmet will mean they'll be deaf every time it fires, same with the loader if they're behind.

**Comment by BonniePandora** [comment]
> This slight issue is soulful, but I'm just making sure it's intended: the AT gunner not having an ear protection helmet will mean they'll be deaf every time the RPG fires, same with the loader if they're behind.

`
	armor_bomb = CLOTHING_ARMOR_MEDIUMHIGH
	flags_inventory = BLOCKSHARPOBJ
	clothing_traits = list(TRAIT_EAR_PROTECTION) //So I don't have to make another subtype for the rocketeers
`

New flags on the Army helmet, they do in fact have hearing protection! Only one who'll be missing from the main combat mooks is the LT

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Doubleumc — APPROVED** [review]

**Pull request merged**
