### PR TITLE
M108 Canister, Redux

### PR DESCRIPTION
**Pull request by KoishiVibe**
# summary 
killed the old one
im going to kill john  git with a claw hammer
- M108 is a spacemaker. It doesn't deal a lot of damage and has zero AP, it won't affect crushers at all. It can however open up vital space in a push or in a defense. But being a grenade means it takes up a lot of space, which might be utilized otherwise by actual lethal weapons.

### CODE REVIEW

**Review by morrowwolf — COMMENTED** [review]
Similar to the other, I'd like to take a look at this before merge. Undraft when you're ready.

**Comment by KoishiVibe** [comment]
> Similar to the other, I'd like to take a look at this before merge. Undraft when you're ready.

eventually
kinda overwhelmed right now
and im like
not vibing 
which is pain

**Comment by FslashN** [comment]
Going to close this for now. Feel free to re-open when you come back to it.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
