### PR TITLE
Tank Equipment Tweaks

### PR DESCRIPTION
**Pull request by ILikeToGammon**
# About the pull request
This PR places the tank on the level of the AA apc, and movie like APC. Currently it changes the fire rate of the AC3-E Autocannon, increases the damage of the LTAA Minigun, increases the damage of the tow launcher, increases the damage of the LTB, and increases the slash and bullet resistance of ballistic armor. I have tested these changes on my own local server but I believe these balance changes needs further testing.

# Explain why it's good for the game
To illustrate the point of why I buffed the tank's equipment, have a look at this meme I created.
image
Before I changed these values, the tow launcher only did about 100 damage when compared to the AA VLS launcher which did 300. The LTAA did 45 damage each bullet which made it feel extremely weak for an AP minigun. I buffed the LTB cannon from 200 damage to 300 damage because it is only capable of doing area damage and bounces off targets.

# Testing Photographs and Procedure

My testing procedure consisted of me spawning a tank with the required equipment and spawning 1 crusher first and then 5 drones. For the TOW launcher it took 2 rockets to kill a crusher and one to kill a drone. The LTAA did admirably against a horde of drones with the increasing firerate turning the gun into a lawnmower. The autocannon was fine in terms of damage but fired extremely slowly. The LTB struggled to kill a crusher but did extremely well against a crowd of drones.

<details>
<summary>Screenshots & Videos</summary>

</details>

# Changelog

:cl:
balance: Increased LTAA damage from 40 to 125
balance: Increased Tow Launcher damage from 10 to 200
balance: Increased LTB damage from 200 to 300
balance: Increased bullet and slash resistance of Ballistic armor to 0.87
balance: Changed Autocannon fire rate from 0.7 seconds to 0.5 seconds
/:cl:

### CODE REVIEW

**Comment by private-tristan** [comment]
Why are there CAS changes in this tank PR?

Also you're touching AP rockets, which means that SADARs will be effected by this change as well (an extra 200 damage on an AP rocket direct hit is crazy).

**Comment by ILikeToGammon** [comment]
To be absolutely honest? I have no idea. I created a new branch for these changes

**Comment by ILikeToGammon** [comment]
Also with the rocket changes do I decrease them or create a new datum for the tow launcher like how the AA VLS has its own one

**Comment by ILikeToGammon** [comment]
Also one more question if I hit delete file on the CAS stuff would it delete all the CAS stuff I changed for the my other PR or would it just delete the changes in regards to this PR

**Comment by ILikeToGammon** [comment]
Also I realized that I am blind and there is a field for the tow launcher

**Pull request closed without merging**
