### PR TITLE
[s] [TM ONLY] Operation code

### PR DESCRIPTION
**Pull request by Zonespace27**
Don't merge this, also don't look through this if you're planning on playing the operation please

~~Will close immediately, closed PRs can be TMed~~

### CODE REVIEW

**Comment by Zonespace27** [comment]
Done running this for now

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Pull request closed without merging**
