### PR TITLE
Better MediHUD

### PR DESCRIPTION
**Pull request by AmoryBlaine**
Marine Corpsman Medical HUD overlay now displays both squad info AND medical info

### CODE REVIEW

**Comment by DexterDude** [comment]
sovl

**Review by AndroBetel — CHANGES_REQUESTED** [review]
fucks up people running no helmets (thats ok)
fucks up movielike smartgunners (its over)
fucks up forecon (its over)
fucks up corpsman (its over)
having weird sans undertale blue eye overlayed over your face at all times could be annoying

i'll keep it in draft for some time, but i doubt there's a way to fix all these problems. 

if you don't like the HUD - just turn it off yourself and use the visor.

**Comment by AmoryBlaine** [comment]
>fucks up people running no helmets (thats ok) 
>
Agreed
>fucks up movielike smartgunners (its over)
>
eh
>fucks up forecon (its over)
>
This doesn't change their earpieces, they still have HUD enabled since I haven't figured out what to do with them yet.
>fucks up corpsman (its over)
>
Just updated that, no longer an issue
>having weird sans undertale blue eye overlayed over your face at all times could be annoying
>
They're unobtrusive, light blue, and translucent. Also, see "fucks up movielike smartgunners". HUDs are movielike, so I'll answer to movielike with movielike
>if you don't like the HUD - just turn it off yourself and use the visor.
>
I called it justified Helmet HUD cause the intention is to encourage usage of the helmet HUDs. Not so that I on an individual level use them

**Comment by bearrrrrrrr** [comment]
please no

already have enough problem getting ppl to follow the fucking sl lmao

**Comment by Eonoc** [comment]
Somewhat late and of dubious usefulness but as to the "fucks up movielike smartgunners", could add a squad HUD element to the smartgun eyepiece, since at present it offers no function.

**Comment by Max-023** [comment]
> Somewhat late and of dubious usefulness but as to the "fucks up movielike smartgunners", could add a squad HUD element to the smartgun eyepiece, since at present it offers no function.

This, since the new M56 goggles have better visuals and could easily act as the SG 'HUD'

**Pull request closed without merging**
