### PR TITLE
grenades

### PR DESCRIPTION
**Pull request by AmoryBlaine**
- Updates grenade sprites to be more accurate, albeit less obvious when deployed (good luck).
-  Removes legacy beeping, adds new activation sound to communicate to the user that the grenade is being deployed, not to the enemy receiving the grenade
- Adds fragmentation to HEDPs to increase their use against human targets, in prep for human AI combatants
- Teargas and flashbangs are no longer police skill locked

### CODE REVIEW

**Comment by BonniePandora** [comment]
New activation sound is good, not a fan of the removal of the visual tell when it's deployed though.
It's **far** too easy to miss a grenade being primed in the midst of combat with chat-log spam even if you have the word 'grenade' highlighted. 
Besides that, the active-sprites look good, with the caps removed.

**Comment by AmoryBlaine** [comment]
You still get the exclaimation marker. I need to add the ability to emote
the frag out line.

**Comment by BonniePandora** [comment]
Oh that's still present? Okay, **much** less worrying then

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
