### PR TITLE
Sorokyne Strata Patch

### PR DESCRIPTION
**Pull request by Max-023**
# About the pull request
Removes all USCM vendors and replaces them with UPP counterparts, as well as USCM gear. CMB equipment is also replaced with UPP equipment to make Sorokyne Strata more adequately feel like a UPP colony. Removes some PVP oriented stuff as well.

# Explain why it's good for the game
Sorokyne is a good map held back by inconsistencies regarding the items there. There is a plentiful amount of USCM and CMB equipment and vendors that do not make sense to be on a UPP colony, especially where there are UPP counterparts that exist in code.

# Testing Photographs and Procedure
N/A

# Changelog

:cl:
add: on Sorokyne, UPP 'Territorial Guard' vendor to replace USCM MP Vendors
del: on Sorokyne, removed USCM Galley Vendors
fix: on Sorokyne, Replaces USCM/CMB guns, ammunition, and belts with UPP counterparts
/:cl:

### CODE REVIEW

**Comment by AmoryBlaine** [comment]
Territorial Guard are military units, the sec vendors should make reference to the People's Police instead

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Doubleumc — APPROVED** [review]

**Review by Doubleumc — CHANGES_REQUESTED** [review]
Code good, but make each changelog line specify that it is changing just Sorokyne. In the changelog people will only see a contextless line like `Replaces USCM/CMB guns, ammunition, and belts with UPP counterparts` and get the entirely wrong idea.

**Review by Doubleumc — APPROVED** [review]

**Pull request merged**
