### PR TITLE
US Armed Forces update 2; the search for more military-prop variety

### PR DESCRIPTION
**Pull request by BonniePandora**
# About the pull request

Expands upon the groundwork laid down in #468 by adding gear presets for both US Aerospace Force and US Army personnel, both props and specialists that might be attached to a deploying marine section/platoon. 

- [X] USASF Jobs
- [X] USASF Skills
- [X] USASF Gear & Presets
- [X] New radio channels for both branches
- [x] Getting the radio channels to _work_
- [X] US Army Jobs
- [X] US Army Skills
- [X] US Army Gear & Presets
- [X] Branch Patches
- [x] Specific Unit-Patches for both branches

# Explain why it's good for the game

More variety in gear for props allows for GM's to craft a richer and more tailored tale for the players to discover throughout the round. For example, perhaps a derlict Almayer was in fact manned by USASF crew on it's way to the shipbreaking yards before falling out of contact? Or maybe a US Army platoon gets into trouble on the planet the Garrow finds itself over and the marines are sent in to help them out?
These are just some examples, but the hope is that it gives GM's more choice in setting things up.

# Testing Photographs and Procedure
Tested consistently throughout the process of coding this mess, compiles and runs on local fine.
Only issue as mentioned above is the radio channels not working in their current state.

<details>
<summary>Screenshots & Videos</summary>

**USASF PERSONNEL**
image
Roster in order;
Para-Rescue Support Technician, Orbital Fire-Support Liason Officer, Hospital Corpsman, USASF Synthetic
Flight-Deck Crew, Enlisted in blue, Flight Boss in khaki with yellow jacket
Basic Crewman, Damage-Control Crewman, Engineering Technician, Duty Officer, Engineering Duty Officer, Commanding Officer

**ARMY PERSONNEL**
image
Roster in order;
Trooper, Sapper, Combat Medic
Fireteam Leader, Squad Leader, Platoon Officer

**New Patches**
image

</details>

# Changelog

:cl:
add: Adds job, skills & gear presets for USASF Personnel
add: Adds job, skills & gear presets presets for US Army Personnel
add: Added Warrant Officer rank paygrades for USCMC
add: Orange-tinted BiMex shades added to the loadout selection
spellcheck: Some typos fixes as I discovered them whilst working on this
imageadd: Added new branch-patches for the Army & USASF
imageadd: Added new Warrant-Officer rank-boards and changed the paygrades to use them for the corresponding ranks
/:cl:

### CODE REVIEW

**Review by Doubleumc — APPROVED** [review]
As far as I can tell, everything is in order here. Let's get this tested.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by BonniePandora** [comment]
> As far as I can tell, everything is in order here. Let's get this tested.

Radios are still borked, not sure what I'm missing for it though that's causing that.
If it's down to the channel prefixes not working I might just see if pilfering the delta and echo prefix is viable, given I don't think those squads are ever used.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by BonniePandora** [comment]
Okay, as of this commit the radio channels work now for US Army & USASF
Adjusted the headsets further, default ones lack comms with marine forces, 'attache' variants feature alpha-squad comms so that joint ops are possible (only the JFO and Para-Rescue tech have this comm-key by default)

**Review by Doubleumc — APPROVED** [review]
Everything looks good.

**Pull request merged**
