### PR TITLE
Adds the ammobearer backpack to the Armory tables

### PR DESCRIPTION
**Pull request by GriffinMan4455**
# About the pull request

Adds the neat backpack that carries ammo boxes to the armory, on the table. Haven't tested, but don't see what this could possibly break.

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying. -->

# Explain why it's good for the game

 I think a single marine in the platoon being able to be a proper dedicated ammobearer is a role we never get to use much, even with how often GM's like to bleed us dry on ammo. This lets a marine forego a backpack in lieu of a more supporting role as "guy hauling the majority of our ammo" instead of just leaving unattended magazine cases in the dropship, or having to carry them by hand. I might make a seperate PR to balance-adjust how many cans this backpack can carry, down the line.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added the ammobearer backpack, the one that carries three ammo cans, to the Garrow Armory
/:cl:

### CODE REVIEW

**Comment by DexterDude** [comment]
No, UPP has it and thats acceptable because their ammo carries a lot less. You don't really need to be carrying almost 3000 rounds of ammo on your person. If you wanna be an ammo bearer, just take the box and put it in your back slot and that's more than enough.

**Comment by GriffinMan4455** [comment]
> No, UPP has it and thats acceptable because their magazines hold a lot less. You don't really need to be carrying almost 3000 rounds of ammo on your person. If you wanna be an ammo bearer, just take the box and put it in your back slot and that's more than enough.

Part of the impetus of this was that you _cant_ take boxes on your back anymore, at least last I saw people try  
Unless that was fixed at some point and I never saw

**Comment by DexterDude** [comment]
> > No, UPP has it and thats acceptable because their magazines hold a lot less. You don't really need to be carrying almost 3000 rounds of ammo on your person. If you wanna be an ammo bearer, just take the box and put it in your back slot and that's more than enough.
> 
> Part of the impetus of this was that you _cant_ take boxes on your back anymore, at least last I saw people try Unless that was fixed at some point and I never saw

You should fix that then, but I don't want people carrying 3k rounds on their backs.

**Comment by GriffinMan4455** [comment]
> > > No, UPP has it and thats acceptable because their magazines hold a lot less. You don't really need to be carrying almost 3000 rounds of ammo on your person. If you wanna be an ammo bearer, just take the box and put it in your back slot and that's more than enough.
> > 
> > 
> > Part of the impetus of this was that you _cant_ take boxes on your back anymore, at least last I saw people try Unless that was fixed at some point and I never saw
> 
> You should fix that then, but I don't want people carrying 3k rounds on their backs.

What if I lowered it to two slots then?
And stole the SG belt code to limit it to one 10x24 box and one 10x28 box then

**Comment by DexterDude** [comment]
> > > > No, UPP has it and thats acceptable because their magazines hold a lot less. You don't really need to be carrying almost 3000 rounds of ammo on your person. If you wanna be an ammo bearer, just take the box and put it in your back slot and that's more than enough.
> > > 
> > > 
> > > Part of the impetus of this was that you _cant_ take boxes on your back anymore, at least last I saw people try Unless that was fixed at some point and I never saw
> > 
> > 
> > You should fix that then, but I don't want people carrying 3k rounds on their backs.
> 
> What if I lowered it to two slots then? And stole the SG belt code to limit it to one 10x24 box and one 10x28 box then

No thank you. Please just fix the back-carrying for the cases, then.

**Pull request closed without merging**
