### PR TITLE
WIP Massive Large Overhaul [skip ci]

### PR DESCRIPTION
**Pull request by AmoryBlaine**
Massive WIP. Restructures all the clothes related code organization, and dmi storage, deletes massive swaths of stuff irrelevant to PvE that interacts with clothes, also redesigns gear presets to be PvE-minded. Massive WIP

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Drulikar** [comment]
Please keep `[skip ci]` in title until this is working locally for you. It has runaway actions that are not completing so indefinitely holding up actions for the organization.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Drulikar** [comment]
Please test changes locally first and get it into a mostly working state before spamming actions that are struggling to complete from the massive amount of errors as well as space/time on IDB and MDB that we're graciously allowed to use.

**Pull request closed without merging**
